# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codezero < Formula
  desc "Collaborative Local Microservices Development."
  homepage "https://codezero.io/"
  version "3.0.0"

  on_macos do
    on_intel do
      url "https://storage.googleapis.com/c6o-releases-staging/3.0.0/headless-darwin-amd64.tgz", using: CurlDownloadStrategy
      sha256 "5cb08627b6d9a0c1d3995095f51e1dd74ba5e1fc1cfc8c15b16a550bedca02f9"

      def install
        bin.install "czctl"
        bin.install "czdaemon"
        bin.install "czsupervisor"
      end
    end
    on_arm do
      url "https://storage.googleapis.com/c6o-releases-staging/3.0.0/headless-darwin-arm64.tgz", using: CurlDownloadStrategy
      sha256 "7d9f10ac7a0c32b582482e4e0c718a325c7b905397161a25d54fc3e370a80f42"

      def install
        bin.install "czctl"
        bin.install "czdaemon"
        bin.install "czsupervisor"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://storage.googleapis.com/c6o-releases-staging/3.0.0/headless-linux-amd64.tgz", using: CurlDownloadStrategy
        sha256 "d963f87b3eb03f3b896770c8ae98547c59d0c956e029dba2b25bad82dfd19f9b"

        def install
          bin.install "czctl"
          bin.install "czdaemon"
          bin.install "czsupervisor"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://storage.googleapis.com/c6o-releases-staging/3.0.0/headless-linux-arm64.tgz", using: CurlDownloadStrategy
        sha256 "136f79a5c3aa2ff435f28480f825e9809f928a7fbe498cb4070bf66ffd9d754b"

        def install
          bin.install "czctl"
          bin.install "czdaemon"
          bin.install "czsupervisor"
        end
      end
    end
  end

  test do
    system "#{bin}/czctl version"
  end
end
