# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codezero < Formula
  desc "Collaborative Local Microservices Development."
  homepage "https://codezero.io/"
  version "3.0.5"

  on_macos do
    on_intel do
      url "https://storage.googleapis.com/c6o-releases-staging/3.0.5/headless-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "5e0737c5fc93a8b90137c97a4e2c0b2f173519f11d1601618fe34d652522c6ac"

      def install
        bin.install "czctl"
        bin.install "czdaemon"
        bin.install "czsupervisor"
      end
    end
    on_arm do
      url "https://storage.googleapis.com/c6o-releases-staging/3.0.5/headless-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7039d71949820291d227037cc0ff6cea76f47bcad553e06cf46eacc19b0f8a27"

      def install
        bin.install "czctl"
        bin.install "czdaemon"
        bin.install "czsupervisor"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://storage.googleapis.com/c6o-releases-staging/3.0.5/headless-linux-amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "2ea65c6101e03d1e4d11446f3d4b5a085d2d4d54742300fc613078b670544937"

        def install
          bin.install "czctl"
          bin.install "czdaemon"
          bin.install "czsupervisor"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://storage.googleapis.com/c6o-releases-staging/3.0.5/headless-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "ef6f0671b5e9379e6f6e150a199f9d2c8383d589e7c6043dc1917ca0f8a67606"

        def install
          bin.install "czctl"
          bin.install "czdaemon"
          bin.install "czsupervisor"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing  czctl Codezero command tool!
    EOS
  end

  test do
    system "#{bin}/czctl version"
  end
end
