# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodezeroATBeta < Formula
  desc "Collaborative Local Microservices Development"
  homepage "https://codezero.io/"
  version "2.7.0-beta1"

  on_macos do
    on_intel do
      url "https://releases.codezero.io/2.7.0-beta1/headless-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "235ebdf5b2cf91b0892daae477b2d28c1c954ccbb96174bdec92f3b6be423d11"

      def install
        if File.exist?("/usr/local/bin/codezero")
          raise "A version not installed by Homebrew has been detected. Please run the following command to uninstall it: curl -L https://releases.codezero.io/uninstall.sh | /bin/bash"
        end
        bin.install "czctl"
        (bash_completion/"czctl").write `#{bin}/czctl completion bash`
        (fish_completion/"czctl.fish").write `#{bin}/czctl completion fish`
        (zsh_completion/"_cztl").write `#{bin}/czctl completion zsh`
      end
    end
    on_arm do
      url "https://releases.codezero.io/2.7.0-beta1/headless-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0392bdeea838e6ca4cd2ef597f2952997e7ec069f673b5d3b2f376d6b2d811af"

      def install
        if File.exist?("/usr/local/bin/codezero")
          raise "A version not installed by Homebrew has been detected. Please run the following command to uninstall it: curl -L https://releases.codezero.io/uninstall.sh | /bin/bash"
        end
        bin.install "czctl"
        (bash_completion/"czctl").write `#{bin}/czctl completion bash`
        (fish_completion/"czctl.fish").write `#{bin}/czctl completion fish`
        (zsh_completion/"_cztl").write `#{bin}/czctl completion zsh`
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.codezero.io/2.7.0-beta1/headless-linux-amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "e4ee4e250a8f3b8299588827fac0613d52f36e829536009767a2a3a192eb2ca1"

        def install
          if File.exist?("/usr/local/bin/codezero")
            raise "A version not installed by Homebrew has been detected. Please run the following command to uninstall it: curl -L https://releases.codezero.io/uninstall.sh | /bin/bash"
          end
          bin.install "czctl"
          (bash_completion/"czctl").write `#{bin}/czctl completion bash`
          (fish_completion/"czctl.fish").write `#{bin}/czctl completion fish`
          (zsh_completion/"_cztl").write `#{bin}/czctl completion zsh`
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.codezero.io/2.7.0-beta1/headless-linux-arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "33ef19862db514fe0e1f0cba1b6474c18c6d72834996e9d61e8ca03a86d78b27"

        def install
          if File.exist?("/usr/local/bin/codezero")
            raise "A version not installed by Homebrew has been detected. Please run the following command to uninstall it: curl -L https://releases.codezero.io/uninstall.sh | /bin/bash"
          end
          bin.install "czctl"
          (bash_completion/"czctl").write `#{bin}/czctl completion bash`
          (fish_completion/"czctl.fish").write `#{bin}/czctl completion fish`
          (zsh_completion/"_cztl").write `#{bin}/czctl completion zsh`
        end
      end
    end
  end

  conflicts_with "codezero"

  def caveats
    <<~EOS
      Successfully installed Codezero 2.7.0-beta1
      Run 'czctl help' or visit https://hub.codezero.io to get started

      Docs: https://docs.codezero.io
      Help: mailto:support@codezero.io
    EOS
  end

  test do
    system "#{bin}/czctl version"
  end
end
